# /etc/greetd/config.toml
[terminal]
vt = 7

[initial_session]
command = "niri-session"
user = "libor"

[default_session]
# The command to start tuigreet
command = "tuigreet --greeting 'Vítejte v endeavourOS' --asterisks --time --time-format '%A, %d. %B %Y • %H:%M:%S' --remember --remember-session --power-reboot 'systemctl reboot' --power-shutdown 'systemctl poweroff' --cmd 'niri-session'"
# The user that runs the greeter
user = "greeter"


